export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_RESET = "REGISTER_RESET";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS";
export const GET_USER_LIST = "GET_USER_LIST";

export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_FAILED = "DELETE_FAILED";

export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_LIST = "UPDATE_LIST";

export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const REFRESH_SUCCESS = "REFRESH_SUCCESS";
export const REFRESH_FAILED = "REFRESH_FAILED";
export const LIST_REFRESH_REQUEST = "LIST_REFRESH_REQUEST";
