export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS";
export const GET_USER_LIST = "GET_USER_LIST";

export const UPDATE_SUCCESS = "UPDATE_SUCCESS";

export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
